### PR TITLE
Case insensitive filter when inserting a part

### PR DESCRIPTION
**Pull request by leoheck**
Hey Zolko, this PR improves the Insert part with Case insensitive filter.

### CODE REVIEW

**Comment by Zolko-123** [comment]
That didn't work. This works, can you please check ? (and please don't mix whitespace cleanups with real code. Also, please do PRs against the development branch)

```
            match_object =  re.search(filterStr, item.text(), flags=re.IGNORECASE)
            if filterStr:
                if match_object:
                    item.setHidden(False)
                else:
                    item.setHidden(True)
            else:
                item.setHidden(False)
```

**Comment by Zolko-123** [comment]
shorter even

```
            # check the items's text match the filter ignoring the case
            match_object =  re.search(filterStr, item.text(), flags=re.IGNORECASE)
            if filterStr and not match_object:
                item.setHidden(True)
            else:
                item.setHidden(False)

```

**Comment by leoheck** [comment]
Yeah, I decided to not remove the old code... this filerStr test was already there. 
But I am testing this while using it a bit, it finds more things than it should find. 
I am thinking that the `item.text()` has extra data that is not being shown in the results. 
Did you try to use it? I am thinking I have to debug the results more.

**Comment by leoheck** [comment]
> (and please don't mix whitespace cleanups with real code.

I did not do any whitespace cleanup.

**Comment by leoheck** [comment]
Indeed, that is working better. I was still testing and the results were a bit wrong. Thanks, dude.

**Comment by Zolko-123** [comment]
Thank-you, I copied the function by hand, (I didn't include all the " _Name :_ " modifications). This is now in the latest release

**Pull request closed without merging**
