### PR TITLE
 infoPartCmd workable

### PR DESCRIPTION
**Pull request by FarmingSoul**
make workable infoPartUI and go out customisable configuration file for key and autoscript

### CODE REVIEW

**Comment by Zolko-123** [comment]
Thanx.

For info, you can get the wbpath with Asm4.wbPath, and it's better to build full file path with os.path.join rather than concatenation strings because it's OS agnostic. If you could make those changes would be helpful, or I'll make them by hand.             

`"Pixmap" : os.path.join( Asm4.iconPath , 'Asm4_PartInfo.svg')`

**Comment by FarmingSoul** [comment]
Hello @Zolko-123 ,

I use os.path.join . Thank you.

**Comment by FarmingSoul** [comment]
Hello @Zolko-123 ,

I am beginner in GitHub and I have a bad level in english , so perhaps I 've got a difficulty to understand some things.

I make separate PR for InfoPartCmd.
I change the path like you say.

Now what can I do ?

I wait for give you a PR for makeBom.

And actually I work on the standard profiles maker . And it look nice. 

After I will work on the configuration of infopart trough the UI and the same for standard profile maker. 

What you think about all that ?

Thanks for your time .

Have nice day .

**Comment by Zolko-123** [comment]
thank-you for this PR, I'll merge it ASAP, but there was an urgency in another command that had bugs. And yes, please submit the PR about the BoM.

**Comment by Zolko-123** [comment]
I merged, and there were 2 errors for the 2 init files. This is fixed now:

```
InfoKeysFile       = os.path.join( wbPath, 'InfoKeys.py' )
InfoScript         = os.path.join( wbPath, 'InfoScript.py' )
InfoKeysFileInit   = os.path.join( wbPath, 'InfoKeysInit.py' )
InfoScriptInit     = os.path.join( wbPath, 'InfoScriptInit.py' )
```

I have to understand now what you're doing here.

**Comment by FarmingSoul** [comment]
hello @Zolko-123 ,

sorry for my absence. 
I will make a small graph to explain how I see the possible operation.

Have nice day

**Comment by FarmingSoul** [comment]
hello @Zolko-123 ,

it must be assumed that the info labels are almost unique to each user by the very principle of the use of this info.

externalfile

what you think about ?

Bye .

**Pull request merged**
