### PR TITLE
v0.11.0

### PR DESCRIPTION
**Pull request by Zolko-123**

### CODE REVIEW

**Comment by FarmingSoul** [comment]
at my home it make that when i insert a part in assembly :
```
18:40:58  Running the Python command 'Asm4_placeLink' failed:
Traceback (most recent call last):
  File "C:\Users\utilisateur\Desktop\FreeCAD_0.20.25541_Win-LPv12.5.4_vc17.x-x86-64\Mod\FreeCAD_Assembly4-master\placeLinkCmd.py", line 85, in Activated
    ui = placeLinkUI()
  File "C:\Users\utilisateur\Desktop\FreeCAD_0.20.25541_Win-LPv12.5.4_vc17.x-x86-64\Mod\FreeCAD_Assembly4-master\placeLinkCmd.py", line 223, in __init__
    self.initUI()
  File "C:\Users\utilisateur\Desktop\FreeCAD_0.20.25541_Win-LPv12.5.4_vc17.x-x86-64\Mod\FreeCAD_Assembly4-master\placeLinkCmd.py", line 752, in initUI
    self.XtranslSpinBox.setValue(self.old_LinkPosition[0])
  File "C:\Users\utilisateur\Desktop\FreeCAD_0.20.25541_Win-LPv12.5.4_vc17.x-x86-64\Mod\FreeCAD_Assembly4-master\Asm4_libs.py", line 838, in setValue
    super().setValue(float(App.Units.schemaTranslate(

could not convert string to float: '0,00'
```

**Comment by Zolko-123** [comment]
sh****t, I knew this was a bad idea (use for imperial units)

**Comment by Zolko-123** [comment]
this is because 0.00 ≠ 0,00

**Comment by Zolko-123** [comment]
```
>>> float('100')
100.0
>>> float('100.0')
100.0
>>> float('100,0')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: could not convert string to float: '100,0'
```

**Comment by Zolko-123** [comment]
> at my home it make that when i insert a part in assembly :
> 
> ```
>   File "C:\Users\utilisateur\Desktop\FreeCAD_0.20.25541_Win-LPv12.5.4_vc17.x-x86-64\Mod\FreeCAD_Assembly4-master\placeLinkCmd.py", line 752, in initUI
>     self.XtranslSpinBox.setValue(self.old_LinkPosition[0])
> ```

could you please test the following: replace in file _C:\Users\utilisateur\Desktop\FreeCAD_0.20.25541_Win-LPv12.5.4_vc17.x-x86-64\Mod\FreeCAD_Assembly4-master\placeLinkCmd.py_ the 3 occurrences or `Asm4.QUnitSpinBox(form)` by `QtGui.QDoubleSpinBox(form)` and check whether that solves the issue ?

**Comment by Zolko-123** [comment]
I update to v0.11.1 to revert this change, can you please update the workbench and test whether the problem is solved ?

**Comment by FarmingSoul** [comment]
for me the probleme it over in v0.11.1
Thank you

**Pull request merged**
