### PR TITLE
Update makeBomCmd.py

### PR DESCRIPTION
**Pull request by FarmingSoul**
workable BoM used Info of InfoPartUI to Spreadsheet

### CODE REVIEW

**Comment by Zolko-123** [comment]
what is the "test.py" ?

**Comment by FarmingSoul** [comment]
Hello @Zolko-123  ,
it is possible to merge without the commit "test profile creator" or i have to remake a new PR with only makeBomCmd ??
sorry and thanks

**Comment by FarmingSoul** [comment]
"test.py" is a test to profile creator UI but he has nothing to do there

**Comment by FarmingSoul** [comment]
hello @Zolko-123 ,

i delete the test of profile maker.
thank i learn a lot

**Comment by Zolko-123** [comment]
Thanx, I merge

**Comment by Zolko-123** [comment]
Hello, I cleaned-up the file infoPartCmd to be more Asm4-like, mostly cosmetic stuff

**Comment by Zolko-123** [comment]
- I removed InfoScript.py: we don't execute arbitrary code from outside the workbench !
- I removed references to infoPartCmd from makeBomCmd (an command should be self-contained)
- I removed the creation of part-info when none was present (a BOM should be passive)
- I corrected the ensuing BUG when info was missing

**Comment by Zolko-123** [comment]
also, there are lots of unused code (commented out) and some un-documented code (in the spreadsheet). Could you please clean up a little ?

**Comment by FarmingSoul** [comment]
>>>* I removed the creation of part-info when none was present (a BOM should be passive)
i make that because of -> if you forget to put a info on a part , these part will forget on a BoM
but if you see on a BoM a part with a false name you know they exist.
(the scrpt self filled some info)

**Comment by FarmingSoul** [comment]
yes i will clean the rest

**Pull request merged**
