### PR TITLE
Features for ExpressionArray

### PR DESCRIPTION
**Pull request by Jolbas**
Added support for lines and circles as Axes. Added support for Scaling which led to a Mirror Array replacing mirrorPart. An evaluation order solver for expressions because the builtin resolver couldn't handle sub-propertys of a placement property. A limitation that hindered a lot of creative and simpler solutions. Side effect: Twice as fast. Shortened property names for them to fit better in expressions and Property view. Using a PropertyLinkSub as Axis which can hold subelements property, As a consequence, removed AxisXYZ

### CODE REVIEW

**Comment by Jolbas** [comment]
I found a bug in the evaluation order function and am trying to fix it now

**Comment by Zolko-123** [comment]
thanx

**Comment by Zolko-123** [comment]
the mirror feature is also very nice ! The capability to chose an LCS axis for the symmetry plane is fantastic !!!

**Comment by Jolbas** [comment]
Yes, that turned out to be useful. With this PR I am enough satisfied with the ExpressionArray to start encourage others to use it. I have for example no more needs renaming and rearranging parameters that could break already made documents. What do you think? Something that bother you in its structure?

**Comment by Zolko-123** [comment]
for now I've not seen any showstopper, it's a great improvement overall, thank-you.

If you have some available time and motivation, the next BIG THING would be the inclusion of the A2+ solver with Asm4. See #387

**Comment by Jolbas** [comment]
Ok. I will look at it and see if I can find motivation. If so, I will eventually find the time too.

**Pull request merged**
