### PR TITLE
render distance measurement using unit preferences

### PR DESCRIPTION
**Pull request by xoviat**
This adds the units specified in the preferences dialog to the distance measurement. There are other locations where it can be added, if you like the idea. Don't merge this PR just yet, but let me know what you think about this.

image

### CODE REVIEW

**Comment by Zolko-123** [comment]
Yes, this is a good idea.

**Comment by xoviat** [comment]
If there's nothing else, this looks good on my end.

**Comment by Zolko-123** [comment]
I never make changes to the master branch, always only to the development branch, and then merge the development branch into the master branch

**Comment by Zolko-123** [comment]
Could you please make another PR against the development branch please ? Sorry for the inconvenience

**Pull request merged**
