### PR TITLE
Low hanging fruit bug fixes

### PR DESCRIPTION
**Pull request by JonasThomas**
I think this might be my first pull request... 
Let me know if you need additional info.

### CODE REVIEW

**Comment by Zolko-123** [comment]
Thank-you for your help, but as it is this PR included too many changes. Please separate really trivial fixes from more complicated functional code

**Comment by JonasThomas** [comment]
I was working on this when I was between jobs.  At this point, my new position is sucking up my band width.

**Comment by JonasThomas** [comment]
> @JonasThomas Any news on this? I think that those bug fixes would be great to get included - Thank you for your work! :)
@Tectu
I was working on this when I was between jobs.  At this point, my new position is sucking up my band width and haven't had time to look at it.

**Comment by Zolko-123** [comment]
bah, since this only changes BoM and PartInfo which are broken anyway, why not try this one

**Pull request merged**
