### PR TITLE
Indicate to the Addon-Manager anytree is a pylib dependency

### PR DESCRIPTION
**Pull request by leoheck**

### CODE REVIEW

**Comment by Zolko-123** [comment]
What would happen if someone wants to install _Assembly4_ but doesn't have `anytree` ?

**Comment by leoheck** [comment]
Right now nothing. It will work normally. Anytree is optional as you asked, and it looks good this way, indeed.
If someone wants to export files, where the `anytree` is needed, it will just give a warning message. 
Now, we could remove the warning when the Asm4 loads since I saw someone mentioning it on Freecad Forum. I just did not know that this was in the latest version released already.

**Comment by leoheck** [comment]
This PR will advertise `anytree` to the Addon Manager, so the user that wants can install it with just one click there. I understood the dependency is not installed automatically.

**Comment by leoheck** [comment]
Hi, this PR changes nothing except it tells the Addon Manager that Asm4 could have this Antree installed. And then The addon manager offers a single-click install makeing the process easier.

**Comment by Zolko-123** [comment]
Did you see the macro [TreeToAscii](https://wiki.freecad.org/Macro%20TreeToAscii) ? It prints the tree in Ascii and outputs it to a window where it's possible to select and then re-use it as text : couldn't it be used to remove the dependency on _anytree_ ? I think this is pretty cool actually for documentation purposes. How does the output on _Tree of Linked Files_ look like ?

```
 └─ asm_LaserCantilever (Model)
     ├─ Origin (Origin)
     │   ├─ X_Axis (X_Axis)
     │   ├─ Y_Axis (Y_Axis)
     │   ├─ Z_Axis (Z_Axis)
     │   ├─ XY_Plane (XY_Plane)
     │   ├─ XZ_Plane (XZ_Plane)
     │   └─ YZ_Plane (YZ_Plane)
     ├─ LCS_Origin (LCS_Origin)
     ├─ Constraints (Constraints)
     ├─ Variables (Variables)
     ├─ LCS_Y (LCS_Y)
     ├─ LCS_X (LCS_X)
     ├─ asm_Y (asm_Y)
     │   ├─ Origin002 (Origin002)
     │   │   ├─ X_Axis002 (X_Axis002)
     │   │   ├─ Y_Axis002 (Y_Axis002)
     │   │   ├─ Z_Axis002 (Z_Axis002)
     │   │   ├─ XY_Plane002 (XY_Plane002)
     │   │   ├─ XZ_Plane002 (XZ_Plane002)
     │   │   └─ YZ_Plane002 (YZ_Plane002)
     │   ├─ LCS_Origin (LCS_Origin)
     │   ├─ Constraints (Constraints)
     │   ├─ Variables (Variables)
     │   ├─ LCS_Sup (LCS_Sup)
     │   ├─ LCS_Inf (LCS_Inf)
     │   ├─ Plaque_Moteur (Plaque_Sup001)
     │   │   ├─ Origin (Origin)
     │   │   │   ├─ X_Axis (X_Axis)
     │   │   │   ├─ Y_Axis (Y_Axis)
     │   │   │   ├─ Z_Axis (Z_Axis)
     │   │   │   ├─ XY_Plane (XY_Plane)
     │   │   │   ├─ XZ_Plane (XZ_Plane)
     │   │   │   └─ YZ_Plane (YZ_Plane)
     │   │   ├─ LCS_0 (LCS_0)
     │   │   ├─ Pad (Pad)
     │   │   │   └─ Sketch_1 (Sketch_1)
     │   │   ├─ Fillet (Fillet)
     │   │   ├─ HoleAxis_1 (HoleAxis_1)
     │   │   ├─ HoleAxis_2 (HoleAxis_2)
     │   │   ├─ HoleAxis_4 (HoleAxis_4)
     │   │   ├─ HoleAxis_5 (HoleAxis_5)
     │   │   ├─ HoleAxis_6 (HoleAxis_6)
     │   │   ├─ HoleAxis_7 (HoleAxis_7)
     │   │   ├─ HoleAxis_9 (HoleAxis_9)
```

**Comment by Zolko-123** [comment]
I have modified that TreeToAscii macro with the option to only show the parts : is this what you wanted to do with _Tree of Linked Parts_ ?

```
 └─ asm_LaserCantilever (Model)
     ├─ asm_Y (asm_Y)
     │   ├─ Plaque_Moteur (Plaque_Sup001)
     │   ├─ Spacer_6mm_1 (Spacer_6mm_1)
     │   ├─ Spacer_6mm_2 (Spacer_6mm_2)
     │   ├─ Spacer_6mm_3 (Spacer_6mm_3)
     │   ├─ Spacer_6mm_4 (Spacer_6mm_4)
     │   ├─ Wheels_1 (Wheels_1)
     │   ├─ Wheels_2 (Wheels_2)
     │   ├─ Wheels_3 (Wheels_3)
     │   ├─ Wheels_4 (Wheels_4)
     │   ├─ Pulley_GT2_14T (Pulley_GT2_14T)
     │   ├─ Rail_20x20 (Rail_20x20)
     │   ├─ Smooth Idler (Smooth_Idler)
     │   ├─ Spacer_3mm_1 (Spacer_3mm_1)
     │   ├─ Spacer_3mm_2 (Spacer_3mm_2)
     │   ├─ Spacer_9mm_1 (Spacer_9mm_1)
     │   ├─ Wheels_5 (Wheels_5)
     │   ├─ Spacer_6mm_5 (Spacer_6mm_5)
     │   ├─ Spacer_9mm_2 (Spacer_9mm_2)
     │   ├─ Spacer_9mm_3 (Spacer_9mm_3)
     │   ├─ Spacer_9mm_4 (Spacer_9mm_4)
     │   ├─ Wheels_6 (Wheels_6)
     │   ├─ Wheels_7 (Wheels_7)
     │   ├─ Wheels_8 (Wheels_8)
     │   ├─ Spacer_6mm_6 (Spacer_6mm_6)
     │   ├─ Spacer_6mm_7 (Spacer_6mm_7)
     │   ├─ Spacer_6mm_8 (Spacer_6mm_8)
     │   ├─ Nema17_X (Nema17_X)
     │   ├─ Nema17_Y (Nema17_Y)
     │   ├─ Pulley_GT2_14T_X (Pulley_GT2_14T_X)
     │   ├─ Black_Angle_1 (Black_Angle_1)
     │   ├─ Black_Angle_2 (Black_Angle_2)
     │   ├─ Belt (Belt001)
     │   ├─ Plaque_Int (Plaque_Int)
     │   ├─ Plaque_Neam17_2trous (Plaque_Neam17_2trous002)
     │   ├─ Plaque_Neam17_1trou (Plaque_Neam17_1trou)
     │   ├─ Pulley_GT2_20T (Pulley_GT2_20T)
     │   ├─ Plate_Nema17 (Plate_Nema17)
     │   ├─ Double_Tnut (Double_Tnut)
     │   ├─ M3x8-Screw (Screw001001)
     │   ├─ M3x8-Screw (Screw001002)
     │   ├─ M3x8-Screw (Screw001003)
     │   ├─ M5-Washer (Washer001001)
     │   ├─ M5-Washer (Washer001002)
     │   ├─ M5-Washer (Washer001003)
     │   ├─ M5-Nut (Nut001001)
     │   ├─ M5-Nut (Nut001002)
     │   ├─ M5-Nut (Nut001003)
     │   ├─ M5-Washer (Washer001004)
     │   ├─ M5-Washer (Washer001005)
     │   ├─ M5-Washer (Washer001006)
     │   ├─ M5-Nut (Nut001004)
     │   ├─ M5-Nut (Nut001005)
     │   ├─ M5-Nut (Nut001006)
     │   ├─ M5x64.0-ThreadedRod (ThreadedRod001)
     │   ├─ M5x64.0-ThreadedRod (ThreadedRod002)
     │   ├─ M5x64.0-ThreadedRod (ThreadedRod003)
     │   ├─ M3x8-Screw001 (Screw001005001)
     │   └─ M3x8-Screw002 (Screw001005002)
     ├─ asm_X (asm_X)
     │   ├─ asm_Mini4Wheel (asm_Mini4Wheel)
     │   │   ├─ Plate_Mini_Wheel (Plate_Mini_Wheel001)
     │   │   ├─ Spacer_6mm_Excentric_1 (Spacer_6mm_Excentric_1)
     │   │   ├─ MiniWheel_1 (MiniWheel_1)
     │   │   ├─ Spacer_6mm_Excentric_2 (Spacer_6mm_Excentric_2)
     │   │   ├─ MiniWheel_2 (MiniWheel_2)
     │   │   ├─ Screw_M5x25_1 (Screw_M5x25_1)
     │   │   ├─ Screw_M5x25_2 (Screw_M5x25_2)
     │   │   ├─ Spacer_6mm_1 (Spacer_6mm_1)
     │   │   ├─ Spacer_6mm_2 (Spacer_6mm_2)
     │   │   ├─ MiniWheel_3 (MiniWheel_3)
     │   │   ├─ MiniWheel_4 (MiniWheel_4)
     │   │   ├─ Screw_M5x25_3 (Screw_M5x25_3)
     │   │   └─ Screw_M5x25_4 (Screw_M5x25_4)
     │   ├─ OptLaser_PLH3D-6W-XF (OptLaser_PLH3D_6W_XF)
     │   │   ├─ M3 d³ugie (M3_d__ugie)
     │   │   ├─ M3 d³ugie (M3_d__ugie001)
     │   │   ├─ M3 d³ugie (M3_d__ugie002)
     │   │   ├─ M3 d³ugie (M3_d__ugie003)
     │   │   ├─ Korpus grawer (Korpus_grawer)
     │   │   ├─ ARK (ARK)
     │   │   └─ PLH3D-6W_Driver_Cover_LONG_Cover_alum (PLH3D_6W_Driver_Cover_LONG_Cover_alum)
     │   ├─ Rail_XT34_40 (Rail_XT34_40)
     │   ├─ M3x8-Screw (Screw001)
     │   ├─ M3x8-Screw (Screw002)
     │   ├─ M3x8-Screw (Screw003)
     │   ├─ cavalier_XT34C2 (cavalier_XT34C2)
     │   ├─ Rail_XT34_gauntry (Rail_XT34_gauntry)
     │   ├─ M5-Washer001 (Washer001)
     │   └─ M5x14-Screw001 (Screw005001)
     ├─ Rail_20x40_Support (Rail_20x40_Support)
     ├─ Plaque_Laterale_AV (Plaque_Laterale_AV)
     ├─ Rail_40x40_Y (Rail_40x40_Y)
     ├─ Plaque_Laterale_AR (Plaque_Laterale_AR)
     └─ Boitier_elec (Boitier_elec001)
```

**Comment by leoheck** [comment]
Thanks. Using the current behavior with the AnyTree. The output looks like this:
image

The output looks exactly the same, I am just listing linked files instead.

Do you have a big design with multiple files to share so I can run this to show a better example of the output? I could not find any files linking multiple files on my computer yet.

**Comment by leoheck** [comment]
Ah found one example.
Here:
image

Or since I am looking at the console
```
Initializing Assembly4 workbench (v0.12.6) ............................. done.
ASM4> Listing linked files in a tree
ASSembly.FCStd
├── sub-assemblies/Base.FCStd
│   ├── cad/FreeCAD-library/2020_V-slot_Al_extrusion/2020x450_V_slot_profile.FCStd
│   ├── cad/FreeCAD-library/2020_V-slot_Al_extrusion/2020x490_V_slot_profile.FCStd
│   └── sub-assemblies/Corner.FCStd
│       ├── cad/FreeCAD-library/Corner/2020_corner_bracket.FCStd
│       └── cad/FreeCAD-library/Slot_T_nuts/Slot_T_nuts.FCStd
├── sub-assemblies/Vertical_frame_XZ.FCStd
│   ├── cad/FreeCAD-library/NEMA/NEMA_17_with_connector.FCStd
│   ├── cad/Side_wood.FCStd
│   ├── sub-assemblies/XZ.FCStd
│   │   ├── cad/Plate_05.FCStd
│   │   ├── cad/FreeCAD-library/NEMA/NEMA_17_with_connector.FCStd
│   │   ├── sub-assemblies/Z_axis.FCStd
│   │   │   ├── cad/Plate_04.FCStd
│   │   │   ├── cad/FreeCAD-library/SC8UU/SC8UU.FCStd
│   │   │   ├── cad/FreeCAD-library/T8_housing_bracket/T8_housing_bracket.FCStd
│   │   │   ├── cad/FreeCAD-library/T8_screw_nut/Anti_backlash_nut/T8_antibacklash_nut_simplified.FCStd
│   │   │   ├── cad/CNC_mount/CNC_mount_V2.FCStd
│   │   │   ├── cad/Mototool.FCStd
│   │   │   ├── cad/Drill_bit.FCStd
│   │   │   └── cad/Googly_eyes.FCStd
│   │   ├── cad/FreeCAD-library/T8_housing_bracket/T8_housing_bracket.FCStd
│   │   ├── cad/FreeCAD-library/SC8UU/SC8UU.FCStd
│   │   ├── cad/FreeCAD-library/T8_screw_nut/Anti_backlash_nut/T8_antibacklash_nut_simplified.FCStd
│   │   ├── cad/FreeCAD-library/SHF08/SHF08.FCStd
│   │   ├── cad/FreeCAD-library/KFL08/KFL08.FCStd
│   │   ├── cad/8mmx300_rod.FCStd
│   │   ├── cad/FreeCAD-library/T8_leadscrew/T8_leadscrew_350mm.FCStd
│   │   ├── cad/Steel L-Bracket for NEMA 17.FCStd
│   │   ├── cad/Timing_pulley_GT2_60.FCStd
│   │   ├── cad/Timing_pulley_GT2_20.FCStd
│   │   ├── cad/Timing_belt_GT2.FCStd
│   │   └── sub-assemblies/SW_Z.FCStd
│   │       ├── cad/FDM/LSW_support_Z.FCStd
│   │       └── cad/step/Limit_SW_PCB.FCStd
│   ├── cad/FreeCAD-library/Coupling/Beam-coupling-8mm-5mm.FCStd
│   ├── cad/8mmx500_rod.FCStd
│   ├── cad/FreeCAD-library/T8_leadscrew/T8_leadscrew_500mm.FCStd
│   ├── cad/FreeCAD-library/SHF08/SHF08.FCStd
│   ├── cad/FreeCAD-library/KFL08/KFL08.FCStd
│   ├── sub-assemblies/Electronics.FCStd
│   │   ├── cad/Board4electronics.FCStd
│   │   ├── cad/step/Arduino_CNC_shield.FCStd
│   │   └── cad/step/Fuente_12V_10A.FCStd
│   ├── cad/FreeCAD-library/Slot_T_nuts/Slot_T_nuts.FCStd
│   ├── cad/Spacer_20.FCStd
│   ├── sub-assemblies/SW_X.FCStd
│   │   └── cad/step/Limit_SW_PCB.FCStd
│   └── sub-assemblies/Green.FCStd
│       ├── cad/FDM/Light.FCStd
│       └── cad/step/Green_indicator.FCStd
├── cad/FreeCAD-library/NEMA/NEMA_17_with_connector.FCStd
├── cad/Steel L-Bracket for NEMA 17.FCStd
├── cad/FDM/NEMA17_support.FCStd
├── cad/FreeCAD-library/Coupling/Beam-coupling-8mm-5mm.FCStd
├── sub-assemblies/3D-printed_corner.FCStd
│   └── cad/FDM/Big_Corner/Big_Corner.FCStd
├── cad/FreeCAD-library/Slot_T_nuts/Slot_T_nuts.FCStd
├── sub-assemblies/Bed_full.FCStd
│   ├── sub-assemblies/Bed_top.FCStd
│   │   ├── cad/Plate_03.FCStd
│   │   ├── cad/Spacer_6.35.FCStd
│   │   └── cad/FreeCAD-library/2020_V-slot_Al_extrusion/2020x370_V_slot_profile.FCStd
│   └── sub-assemblies/Bed_bottom.FCStd
│       ├── cad/FreeCAD-library/SK08/SK08.FCStd
│       ├── cad/FreeCAD-library/KP08/KP08.FCStd
│       ├── cad/8mmx500_rod.FCStd
│       ├── cad/FreeCAD-library/T8_leadscrew/T8_leadscrew_500mm.FCStd
│       └── sub-assemblies/SW_Y.FCStd
│           └── cad/FDM/LSW_support_Y.FCStd
└── sub-assemblies/Emergency.FCStd
    ├── cad/FDM/Emergency_button_case.FCStd
    └── cad/FreeCAD-library/Electrical Switches/EmergencyButton_LAY37.fcstd
ASM4> Listing ended
```

**Comment by Zolko-123** [comment]
you can get that with that macro. It prints relative paths if available and absolute if not. I've attached my modified version of the macro. You have to select something for it to print the tree of the thing (you have to change the extension to FCMacro and place it into the Macro folders)

```
 └─ asm_LaserCantilever @ asm_LaserCantilever.FCStd
     ├─ asm_Y @ sub_Y/asm_Y.FCStd
     │   ├─ Plaque_Moteur @ sub_Y/asm_Y.FCStd
     │   ├─ Spacer_6mm_1 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_6mm_2 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_6mm_3 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_6mm_4 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Wheels_1 @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Wheels_2 @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Wheels_3 @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Wheels_4 @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Pulley_GT2_14T @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Rail_20x20 @ Library/OpenBuilds/Rail_V-Slot_20x20.FCStd
     │   ├─ Smooth Idler @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Spacer_3mm_1 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_3mm_2 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_9mm_1 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Wheels_5 @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Spacer_6mm_5 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_9mm_2 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_9mm_3 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_9mm_4 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Wheels_6 @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Wheels_7 @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Wheels_8 @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Spacer_6mm_6 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_6mm_7 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Spacer_6mm_8 @ Library/OpenBuilds/Spacers.FCStd
     │   ├─ Nema17_X @ Library/Nema17.FCStd
     │   ├─ Nema17_Y @ Library/Nema17.FCStd
     │   ├─ Pulley_GT2_14T_X @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Black_Angle_1 @ /home/hubertz/Projects/CNC/LaserCut/FreeCAD/Library/OpenBuilds/OB_Brackets.FCStd
     │   ├─ Black_Angle_2 @ /home/hubertz/Projects/CNC/LaserCut/FreeCAD/Library/OpenBuilds/OB_Brackets.FCStd
     │   ├─ Belt @ sub_Y/asm_Y.FCStd
     │   ├─ Plaque_Int @ sub_Y/asm_Y.FCStd
     │   ├─ Plaque_Neam17_2trous @ sub_Y/asm_Y.FCStd
     │   ├─ Plaque_Neam17_1trou @ sub_Y/asm_Y.FCStd
     │   ├─ Pulley_GT2_20T @ Library/OpenBuilds/Wheels.FCStd
     │   ├─ Plate_Nema17 @ sub_Y/asm_Y.FCStd
     │   ├─ Double_Tnut @ Library/OpenBuilds/Screws.FCStd
     │   ├─ M3x8-Screw @ sub_Y/asm_Y.FCStd
     │   ├─ M3x8-Screw @ sub_Y/asm_Y.FCStd
     │   ├─ M3x8-Screw @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Washer @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Washer @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Washer @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Nut @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Nut @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Nut @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Washer @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Washer @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Washer @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Nut @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Nut @ sub_Y/asm_Y.FCStd
     │   ├─ M5-Nut @ sub_Y/asm_Y.FCStd
     │   ├─ M5x64.0-ThreadedRod @ sub_Y/asm_Y.FCStd
     │   ├─ M5x64.0-ThreadedRod @ sub_Y/asm_Y.FCStd
     │   ├─ M5x64.0-ThreadedRod @ sub_Y/asm_Y.FCStd
     │   ├─ M3x8-Screw001 @ sub_Y/asm_Y.FCStd
     │   └─ M3x8-Screw002 @ sub_Y/asm_Y.FCStd
     ├─ asm_X @ sub_X/asm_X.FCStd
     │   ├─ asm_Mini4Wheel @ sub_X/asm_Mini4Wheel.FCStd
     │   │   ├─ Plate_Mini_Wheel @ sub_X/asm_Mini4Wheel.FCStd
     │   │   ├─ Spacer_6mm_Excentric_1 @ Library/OpenBuilds/Spacers.FCStd
     │   │   ├─ MiniWheel_1 @ Library/OpenBuilds/Wheels.FCStd
     │   │   ├─ Spacer_6mm_Excentric_2 @ Library/OpenBuilds/Spacers.FCStd
     │   │   ├─ MiniWheel_2 @ Library/OpenBuilds/Wheels.FCStd
     │   │   ├─ Screw_M5x25_1 @ Library/OpenBuilds/Screws.FCStd
     │   │   ├─ Screw_M5x25_2 @ Library/OpenBuilds/Screws.FCStd
     │   │   ├─ Spacer_6mm_1 @ Library/OpenBuilds/Spacers.FCStd
     │   │   ├─ Spacer_6mm_2 @ Library/OpenBuilds/Spacers.FCStd
     │   │   ├─ MiniWheel_3 @ Library/OpenBuilds/Wheels.FCStd
     │   │   ├─ MiniWheel_4 @ Library/OpenBuilds/Wheels.FCStd
     │   │   ├─ Screw_M5x25_3 @ Library/OpenBuilds/Screws.FCStd
     │   │   └─ Screw_M5x25_4 @ Library/OpenBuilds/Screws.FCStd
     │   ├─ OptLaser_PLH3D-6W-XF @ Library/OptLaser_PLH3D-6W.FCStd
     │   │   ├─ M3 d³ugie @ Library/OptLaser_PLH3D-6W.FCStd
     │   │   ├─ M3 d³ugie @ Library/OptLaser_PLH3D-6W.FCStd
     │   │   ├─ M3 d³ugie @ Library/OptLaser_PLH3D-6W.FCStd
     │   │   ├─ M3 d³ugie @ Library/OptLaser_PLH3D-6W.FCStd
     │   │   ├─ Korpus grawer @ Library/OptLaser_PLH3D-6W.FCStd
     │   │   ├─ ARK @ Library/OptLaser_PLH3D-6W.FCStd
     │   │   └─ PLH3D-6W_Driver_Cover_LONG_Cover_alum @ Library/OptLaser_PLH3D-6W.FCStd
     │   ├─ Rail_XT34_40 @ Library/Thorlabs_XT34.FCStd
     │   ├─ M3x8-Screw @ sub_X/asm_X.FCStd
     │   ├─ M3x8-Screw @ sub_X/asm_X.FCStd
     │   ├─ M3x8-Screw @ sub_X/asm_X.FCStd
     │   ├─ cavalier_XT34C2 @ Library/Thorlabs_XT34.FCStd
     │   ├─ Rail_XT34_gauntry @ Library/Thorlabs_XT34.FCStd
     │   ├─ M5-Washer001 @ sub_X/asm_X.FCStd
     │   └─ M5x14-Screw001 @ sub_X/asm_X.FCStd
     ├─ Rail_20x40_Support @ /home/hubertz/Projects/CNC/LaserCut/FreeCAD/Library/OpenBuilds/OB_Rails.FCStd
     ├─ Plaque_Laterale_AV @ asm_LaserCantilever.FCStd
     ├─ Rail_40x40_Y @ /home/hubertz/Projects/CNC/LaserCut/FreeCAD/Library/OpenBuilds/OB_Rails.FCStd
     ├─ Plaque_Laterale_AR @ asm_LaserCantilever.FCStd
     └─ Boitier_elec @ asm_LaserCantilever.FCStd
```
[TreeToAscii.txt](https://github.com/Zolko-123/FreeCAD_Assembly4/files/10949755/TreeToAscii.txt)

**Comment by leoheck** [comment]
I am not sure what you are proposing. Do you want to remove this feature from Asm4?

**Comment by leoheck** [comment]
Why dont you add the anytree as dependency to the Addon Manager?

This PR does that. IT is a single line addition. It will tell to the user installing Asm4, that there is a module that can be installed to add some extra features to the tool.

**Comment by Zolko-123** [comment]
> I am not sure what you are proposing. Do you want to remove this feature from Asm4?

No, I think this feature is very good. What I'm proposing is to replace it with _TreeToAscii_, either directly or to include a modified version of it. I need more info than only the name of the included file. What I'd like to see in the ascii tree is:

`link_name → linked_object @ filename`

with relative paths when available, absolute paths otherwise. So I'd rather propose improvements to the macro and include the macro

**Comment by Zolko-123** [comment]
I have modified _exportFile_ to remove the dependency. It now uses some code from _TreeToAscii_ macro. Please check, and make modifications if you need. But please don't add external dependencies for an non-core function like this

**Comment by Zolko-123** [comment]
Dependency on _anytree_ has been removed

**Pull request closed without merging**
