### PR TITLE
README: Update + fix markdown + refine

### PR DESCRIPTION
**Pull request by luzpaz**
Preview: https://github.com/luzpaz/FreeCAD_Assembly4/blob/README/README.md

### CODE REVIEW

**Comment by luzpaz** [comment]
@Zolko-123 what minimum FC revision of v0.19 is requires for Assembly4 to work out of the box ?

**Comment by Zolko-123** [comment]
On dimanche 6 octobre 2019 20:36:48 CEST luzpaz wrote:
> @Zolko-123 what minimum FC revision of v0.19 is requires for Assembly4 to work out of the box ?

hi luzpaz,

I tested Asm4 with FreeCAD_0.19-18353, that's revision 18353 minimum if I understand correctly. 

cheers

zoltan




> 
> 


-- 

═══════════════
   HUBERT Zoltán 
═══════════════

**Comment by Zolko-123** [comment]
Are you sure A4 is the best name ? Wouldn't "_Asm4_" be easier to understand ?

**Comment by Zolko-123** [comment]
Hi luzpaz,

There is a problem: 

`cd ~/.FreeCAD/Mod`
`git clone https://github.com/Zolko-123/FreeCAD_Assembly4`

doesn't work with the way I orginised the repository. What needs to go into `~/.FreeCAD/Mod`  is `https://github.com/Zolko-123/FreeCAD_Assembly4/Mod_Asm4`, the subdirectory, not the root.

If it's mandatory to use the gitclone command, then the contents of the _Mod_Asm4_ subdirectory need to go to the root of _FreeCAD_Assembly4_

Should I do that ?

**Pull request merged**
