### PR TITLE
README: Mardown formatting + fixes + readability tweaks

### PR DESCRIPTION
**Pull request by luzpaz**
* Incorporate correct markdown (remove `<br>`'s
* formatting for improved readability  
* typo fixes

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/FreeCAD_Assembly4/tree/README-refinements

**Comment by luzpaz** [comment]
Rebased and included latest change. Please use [markdown](https://guides.github.com/features/mastering-markdown/) instead of HTML.

**Comment by Zolko-123** [comment]
nice, thanx. But ... how do I include your fixes ? (I'm sorry, I don't know how to use GitHube properly)

**Comment by luzpaz** [comment]
So in markdown if you want to specify a new line like you would in HTML via `<br>` you append 2 whitespaces at the end of the sentence (along with a newline) like so:  
The rest of this PR you should merge because it adds those 2 whitespaces at the end of sentences where you haven't. Just merge this PR through the Github gui.

**Comment by luzpaz** [comment]
@Zolko-123  
you can merge it via the GUI. If you're not sure..give me access and I'll do it, then revoke my access after I'm done.

**Comment by Zolko-123** [comment]
On mercredi 7 août 2019 03:51:13 CEST luzpaz wrote:
> @Zolko-123  
> you can merge it via the GUI. If you're not sure..give me access and I'll do it, then revoke my access after I'm done. 

done, thank-you.

now Asm4 needs to be tested with the recently merged App::Link

ciao

zoltan



> 
> 


-- 

═══════════════
   HUBERT Zoltán 
═══════════════

**Pull request merged**
