### PR TITLE
Load asm4 even if anytree is missing

### PR DESCRIPTION
**Pull request by leoheck**

### CODE REVIEW

**Comment by Zolko-123** [comment]
yes, something like that, but I would be even more brutal: if anytree is not available, don't do any of this at all. Like:

```
has_anytree = False
try:
    from anytree import Node, RenderTree
    has_anytree = True
except ImportError:
    FCC.PrintWarning("WARNING : Pylib dependency missing = anytree, exportFiles is not available\n")
    pass

if has_anytree:
    ...
else:
    ...
```
and define dummy commands to prevent errors.

**Comment by Zolko-123** [comment]
I committed a change to make the dependecy optional. At least now Asm4 starts again, please update as you see fit

**Comment by Zolko-123** [comment]
This conflicts now with my workaround. Please update your local repo and improve this solution

**Comment by leoheck** [comment]
What should I do? Don't you want me to update my repo?
Why did you close it?

**Comment by leoheck** [comment]
The latest changes do not work when you do have the anytree. 

I am using the latest dev
image

I have the lib installed
image

And I am seeing this
image

However, I am updating a fix in a new PR.

**Comment by leoheck** [comment]
Here it is https://github.com/Zolko-123/FreeCAD_Assembly4/pull/405

**Comment by leoheck** [comment]
Thanks for your help.

**Pull request closed without merging**
