### PR TITLE
Improvements of Interference Checks with GUI

### PR DESCRIPTION
**Pull request by leoheck**
Thanks for your last fix. I think we are converging on a nice tool.

This time I fixed the missing test I removed last time by mistake, that was important. 

I also improved the console messages. It will print all the comparisons (including the replicated ones) since it is easier for the user to find them and to make sure all the checks are being performed. It will also add under the comparison the status if it is clear, colliding, touching, or already processed. 

Also, if there is no interference, it now removes the folder, restores the visibility of the Model, and prints a message saying the model is clear. (maybe a popup would be better in this case?)

### CODE REVIEW

**Comment by Zolko-123** [comment]
The problem with `print()` is that it doesn't print to the _Report View_, so the user doesn't see the messages. Ideally, we should open a window with a progress bar. Do you think we could estimate the progress of the calculation ?

**Comment by leoheck** [comment]
Hm, did not understand. For me, it does print on Report View.

image

**Comment by leoheck** [comment]
I was about to show you using a bigger project and found and issue. I will try to fix it.

**Comment by leoheck** [comment]
I am going to try to add this percent of comparisons to this PR so we can discuss later, cool?

**Comment by leoheck** [comment]
> The problem with print() is that it doesn't print to the Report View,

Ah, I see what you are saying. You are saying that it does not print while processing. And if you run freecad from the terminal we can see it being printed on each interaction. Got it.

**Comment by leoheck** [comment]
Sometimes when there is no visible part inside a Part, its copy does not produce a visible shape, then the Common is not computed. I improve that. 

image

Now I will try to work on a progress bar/popup.

**Comment by Zolko-123** [comment]
> Ah, I wanted to turn this block here into a function. Since it is used twice. But for some reason, I could not make it work.

Did you look at my version of the file ? 

https://github.com/Zolko-123/FreeCAD_Assembly4/blob/development/checkInterference_z.py

I solved the problem differently: first all shapes are copied (line 72 and `make_shape_copy()` ), then all interferences are checked (line 84 and `parse_interferences()` ) and finally the results are analysed as before (line 88)

Since the number of parts is know – N – the number of interference checks is also known – N*(N-1)/2 – so we should be able to show a progress bar based on that

**Comment by leoheck** [comment]
And we could add an abort button too, =)

**Comment by leoheck** [comment]
I did not look your file, I am going to check it later, today.

**Comment by leoheck** [comment]
Ah, found  that this plane, is generated, sometimes, when the LCS is visible. 
How can I hide the LCSs on python?
image

**Comment by leoheck** [comment]
I am starting to have something.
image

**Comment by leoheck** [comment]
@Zolko-123 I was playing around with the GUI and the progress bar. 
It is not ready to merge since I still have to clean the code and improve the info.
But it is getting interesting.

**Comment by leoheck** [comment]
Just a quick idea how it looks like. Tomorrow I will improve it more. 
image

**Comment by Zolko-123** [comment]
Nice. The "check fasteners" buttons is good idea, although it must not produce an error if the fasteners workbench is not installed. You should leave it for a later improvement. as for the lower buttons, I suggest only 1: "Abort" which becomes "Close" when the calculation is finished. The interferences check is launched right at the beginning, no need for an extra button

Also, I think that [my version](https://github.com/Zolko-123/FreeCAD_Assembly4/blob/development/checkInterference_z.py#L130) of `parse_interferences()` is much shorter and clearer than [the original](https://github.com/leoheck/FreeCAD_Assembly4/blob/interference-check-improvements-NEW/checkInterference.py#L62) `check_interferences()`. In my version, it is done in 2 steps: 1) the shapes of all objects of the correct _TypeId_ (PARTID2CHECK) are duplicated in the _ShapesCopy_ folder, and 2) then these copies are parsed 2-by-2 and the interferences created. I find the data flow of the original function quite complex

**Comment by leoheck** [comment]
Yeah, Insaw your version. I am trying to organize and improve this popup, and later I can improve it to have a.better code. 

Considering fasteners, it doesn't matter if the workbench is installed. it is converted to a Part to be compared. The file cab have fasteners even if the user does not have fasteners workbench installed. but if I am wrong, we could disable the fasteners checkbox of the workbench is not present

**Comment by leoheck** [comment]
I am playing learning and improving the GUI of this feature, did not touch the interference checks yet.

I am committing the code to save the progress. I invite you to check it out to see the progress and discuss the GUI.

I am looking for a way to 
- add colors in the Log View
- scroll the log view to the bottom automatically.

Do you know to do any of those?

image

**Comment by leoheck** [comment]
Alright, I could make it work better. It is more mature now. 

Now it is nice to give it a try to see if it is working for you too, @Zolko-123 
And maybe, to check if it is working with different Assemblies that have more and different types of objects.

Maybe it is good enough to ask people to try it on Freecad Forum, too.

Some things I still want to improve (mostly the GUI).
1. TextEdit has to scroll down automatically with new text.
1. Text can be copied but not edited, I should disable that somehow. 
1. Colors on the `log_view`, would be nice to have. 
1. Set the settings box with a fixed height. So it would work fine when resized.
1. Buttons could be smaller and have a fixed size. 
1. The Abort button could have a red image or something.

A sample of the current thing, here the operation was aborted.
image

Here it ended nice
image

**Comment by leoheck** [comment]
Hi @Zolko-123 , I believe the Interference Check is working quite well now. 
It it is working ok for you without any other request, we could merge this code, to check how it will work for other users too.

**Comment by Zolko-123** [comment]
OK will do

**Comment by Zolko-123** [comment]
Thanks. This is a big chunk so I'll review it and make a new release with that. Then we can go for the BOM

**Comment by leoheck** [comment]
Sure, that would be awesome. I would like to keep changes small, unfortunately, I wanted to improve the whole process this time.

**Pull request merged**
