### PR TITLE
placeLinkCmd: Specify absolute AttachmentOffset (translation and rotation) of linked part, LCS preselection

### PR DESCRIPTION
**Pull request by DerAndere1**
This is targeted at the development branch. If you prefer a pull request targeted at the master branch, you can merge https://github.com/Zolko-123/FreeCAD_Assembly4/pull/137 instead.

This adds SpinBoxes for specifying absolute AttachmentOffset values (translation and rotation) in the "Place Linked Part" dialog.
When opening the dialog, the default values of these SpinBoxes correspond to the original AttachmentOffset of the linked part.

Picture2

Also, if two LCS were selected in the tree view, those LCS are  now pre-selected as attachment-points in the "Place linked Part" dialog.

Usage:

To Move/attach a linked part in an Assembly4 assembly, you now have two options:

workflow a):

1. Select the App::Link for the linked part
2. Clicking the button "Edit Placement of Part" (Tooltip: "Move/Attach a part in the assembly")
3. Optionally, change the values of the SpinBoxes to specify translation and rotation (angle range: -360.00 to 360.00, default: taken from the original AttachmentOffset of the linked part)
4. Optionally, left-click on the button "Rot X + 90°", "Rot Y + 90°" to rotate the AttachmentOffset of the linked part in 90°-steps. The values are taken from the SpinBoxes (see step 3).

workflow b):

1. In the model tree, first select an LCS of the linked part
2. Ctrl + left-click to add to the selection another LCS (in the parent_part) that you want to use as the attachment point
3. Left-click button "Edit Placement of Part" (Tooltip: "Move/Attach a part in the assembly") to open the dialog "Place Linked Part"
4. Observe that the two LCS that were selected in step 1-2 are also preselected in the dialog
5. Optionally, change the value of the SpinBoxes to specify translation and rotation (angle range: -360.00 to 360.00, default: taken from the original AttachmentOffset of the linked part)
6. Optionally, left-click on the button "Rot X + 90°", "Rot Y + 90°" to rotate the AttachmentOffset of the linked part in 90°-steps. The values are taken from the SpinBoxes (see step 5).

**Related feature requests:**

- https://github.com/Zolko-123/FreeCAD_Assembly4/issues/64
- https://github.com/Zolko-123/FreeCAD_Assembly4/issues/85
- https://github.com/Zolko-123/FreeCAD_Assembly4/issues/78

### CODE REVIEW

**Comment by Zolko-123** [comment]
Thank-you, I'll test it now

**Comment by Zolko-123** [comment]
Yes, I like it very much. Especially the translation, not so much the rotation: on a small-ish screen, you don't see the rotation buttons. And rotations with arbitrary values should be done with dedicated attachment LCS. What do you think ? Do you use very often this precise rotation in the placement ? I think it's simpler and cleaner like this :

placeLink

didn't test the pre-selection of LCS yet.

**Comment by Zolko-123** [comment]
as for the pre-selection of LCS, I don't understand how it can work: if you want to attach a link to another link, there is no way to know which one is the link to be placed and which one is the target attachment. Also, there is no getLinkAndDatum2 in this PR, I get an error.

I was rather thinking about a selection observer, where it would be possible to select the LCS in the 3D window, rather than in the tree.

**Comment by DerAndere1** [comment]
The free setting of rotation can be used in cases like a rotating turret where the top-part is connected to a platform in a way that allows rotation but where extrusions from both parts interfere with each other and thus limit the rotation to a small area. The same top-part may rotate freely on another platform, thus the correct rotation of the attachment LCS in the top-part cannot be inferred from the top-part alone. 
On the other hand, I agree that limiting the possibilities for the user to fool around with the rotation in the dialog might enforce a well-thought LCS placement (interface). 

I just saw that by accident I added a duplicate of the function getLinkAndDatum. I rather wanted to

add (taken from my previous PR) the following in libAsm4:

```
# get from two selected datums the corresponding links
def getLinkAndDatum2():
    retval = (None, None, None, None)
    # only for Asm4 
    if checkModel() and len(Gui.Selection.getSelection()) == 2:
        parentAssembly = App.ActiveDocument.Model
        # find all the links to Part or Body objects
        childrenTable = []
        for objStr in parentAssembly.getSubObjects():
            # the string ends with a . that must be removed
            obj = App.ActiveDocument.getObject( objStr[0:-1] )
            if isLinkToPart(obj):
                # add it to our tree table if it's a link to an App::Part ...
                childrenTable.append( obj )

        selObjA = Gui.Selection.getSelection()[0]
        selObjB = Gui.Selection.getSelection()[1]
        # two datum objects are selected
        if ((selObjA.TypeId in datumTypes) and (selObjB.TypeId in datumTypes)):
            # this returns the selection hierarchy in the form 'linkName.datumName.'
            selTreeA = Gui.Selection.getSelectionEx("", 0)[0].SubElementNames[0]
            selTreeB = Gui.Selection.getSelectionEx("", 0)[0].SubElementNames[1]
            (parentsA, totoA, dotA) = selTreeA.partition('.'+selObjA.Name)
            (parentsB, totoB, dotB) = selTreeB.partition('.'+selObjB.Name)
            linkA = App.ActiveDocument.getObject( parentsA )
            linkB = App.ActiveDocument.getObject( parentsB )
            if (dotA =='.' and linkA in childrenTable) and (dotB =='.' and linkB in childrenTable):
                retval = (linkA, selObjA, linkB, selObjB)

            else:
                # see whether the datum objects are in a group, some people like to do that
                (parentsA2, dotA, groupNameA) = parentsA.partition('.')
                (parentsB2, dotB, groupNameB) = parentsB.partition('.')
                linkA2 = App.ActiveDocument.getObject( parentsA2 )
                linkB2 = App.ActiveDocument.getObject( parentsB2 )
                groupA = App.ActiveDocument.getObject( groupNameA )
                groupB = App.ActiveDocument.getObject( groupNameB )
                if ((linkA2 in childrenTable and groupA.TypeId=='App::DocumentObjectGroup') and (linkB2 in childrenTable and groupB.TypeId=='App::DocumentObjectGroup')):
                    retval = (linkA2,selObjA,linkB2,selObjB)

    return retval
```

While we are at it, I will research how to add a selection observer that deals with LCS. I may be able to borrow from the link observer that was added recently to Assembly4

**Comment by Zolko-123** [comment]
yeah, I saw that. I replaced with the new function, and the selection of 2 LCS to infer the attachment isn't very intuitive. Are you sure you want to leave it in ? Anyway, I'll push my mods on your PR.

Thanx

**Comment by DerAndere1** [comment]
Yes leave that in, you do not have to document it. But it allows the workflow described in the last comment of feature request #64. This is great for parts with a lot of LCSs that are best selected with the help of the 3D view. Also: as long as there is no possibility at all in FreeCAD to select two LCS from the 3D view, I cannot think of a good selection observer.

**Comment by Zolko-123** [comment]
When selecting 2 LCS, why do you want to highlight (change the appearence) of the second object ? In the "normal" behaviour, the object to be placed is white transparent in order to recognise it in an assembly. This should also be the case in the "new" behaviour. What is the rationale to also change the appearance of the second object ?

**Comment by DerAndere1** [comment]
changing the appearance of the second part is not intended. it is rather an artifact due to my brainless copy-paste-modify coding.

I guess it is enought to remove all lines related to selectedLinkB from the following section:

https://github.com/Zolko-123/FreeCAD_Assembly4/blob/480529208ce29ca1edb6c4603876783da50b8c43/placeLinkCmd.py#L284-L292

**Comment by Zolko-123** [comment]
You duplicated ALL the code ?????? You can't be serious ... also, it doesn't work correctly: when I select 2 LCS, it does highlight them in the selection list, but it doesn't place the link to where it should go. I have to change some selections, and then go back again, to put the link where I initially selected.

Next time, please split your PRs into separate functionality: the translation is very good, but this selection thing is not. A selection observer in the 3D window for LCS would be much better. There already is a selection observer for the part : you don't have to select the attachment part in the list, you can select it in the 3D window, and it will select it in the list. The same functionality would be good for the LCS.

**Comment by Zolko-123** [comment]
I remove this dual LCS selection thing. If you **really** need it, please make another PR, but without duplicating **everyting**, because it's unmaintainable.

**Comment by DerAndere1** [comment]
We have the code in my repo in case we want to improve the preselection code. Feel free to take only the bits you like.

**Comment by Zolko-123** [comment]
Nice ... but where is that code ? Couldn't find it

**Pull request merged**
