### PR TITLE
Some updates to documentation

### PR DESCRIPTION
**Pull request by Jolbas**
Also redirected the help menu item to open the instructions on github instead of showing "Lorem ipsum"

### CODE REVIEW

**Comment by Zolko-123** [comment]
why do you want to remove `placeLinkCmd()` ?

**Comment by Jolbas** [comment]
ops. I didn't want that.

**Comment by Zolko-123** [comment]
Good idea to take in the instructions from the repo. I'll check how that works. Thanx

**Comment by Jolbas** [comment]
> Good idea to take in the instructions from the repo. I'll check how that works. 

It won't work at all because I removed too many imports. I thought I tested it bu obviously I didn't. Fixed in https://github.com/Zolko-123/FreeCAD_Assembly4/pull/398

**Pull request merged**
