### PR TITLE
BOM is back to the game

### PR DESCRIPTION
**Pull request by leoheck**
This adds the working BOM again to the game. 
This also includes a way to export all links to a single zip file
Please, it will be good to have people testing it so we can try to solve any possible issue.

### CODE REVIEW

**Comment by Zolko-123** [comment]
```
19:29:20  No module named 'anytree'
19:29:20  Traceback (most recent call last):
  File "<string>", line 143, in Initialize
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/hubertz/.local/share/FreeCAD/Mod/Assembly4_GitHub/./exportFiles.py", line 11, in <module>
    from anytree import Node, RenderTree
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
```

what is "anytree" ?

**Comment by leoheck** [comment]
It is a module to handle graphs.
Can be installed with `pip install anytree`

**Comment by Zolko-123** [comment]
Can you please make the dependency on `anytree` optional ? Right this _Assembly4_ can't load.

For example : if it's there we use it, if not we show a warning and restrict the usage of the BOM to those parts that don't require it.

**Comment by leoheck** [comment]
Sure, the PR is there already. Please, check if this is the way you were thinking of it.

**Comment by leoheck** [comment]
Also, Addon Manager has these Python Dependencies. I am looking for a way to make this dependency to appear there too. Do you have any idea? 

image

**Pull request merged**
