### PR TITLE
Improve version check with a way to disable the annoying popup.

### PR DESCRIPTION
**Pull request by leoheck**
This PR also improves the text of the popup and the msg on the report view.

image

This closes the discussion here, https://github.com/Zolko-123/FreeCAD_Assembly4/discussions/487

### CODE REVIEW

**Comment by 3x380V** [comment]
Solution to the annoying popup (as there is not any).

**Comment by leoheck** [comment]
Hey @3x380V this your fix looks good for me, better than this popup + not having the LCS working and having to edit it  manually one everytime I create a new LCS. Good work, thanks. 

@Zolko-123 , please, take some time to check @3x380V solution.

I am going to close this PR since the alternative solution is better.

**Comment by Zolko-123** [comment]
where can I find  @3x380V's solution ? He seems to have simply removed the warning, or is there something else ?

**Comment by leoheck** [comment]
It is his `devel` branch, this is a fix for him. The LCSs are being generated fine. I understood that if you would like to have this solution merged you should said so and then he will prepare a better PR for this repo. 

He does not need the warning since he has fixed the problem itself which is better.

@3x380V can you please make a PR for us?

**Comment by 3x380V** [comment]
@leoheck PR is open, a few minor changes I consider useful are waiting in my [random_fixes](https://github.com/3x380V/FreeCAD_Assembly4) branch. @Zolko-123 is free to cherry-pick or ask for another PR or ignore.

**Comment by leoheck** [comment]
out of curiosity what are the other random fixes you have? they may be
interesting

**Pull request closed without merging**
