### PR TITLE
add variable name checking

### PR DESCRIPTION
**Pull request by wang02139**
This fixes issue #96 "Add Variable" has error when using a Name with space inside. I've added checks and error handling.

### CODE REVIEW

**Comment by Zolko-123** [comment]
this looks great, thank-you, I'll merge it, but could you please make the PR against the development branch ? I never merge anything directly into the master.

**Comment by wang02139** [comment]
Thanks. I'll use development branch next time.

**Comment by Zolko-123** [comment]
Hello,

what is `pattern = re.compile("^[A-Za-z][_A-Za-z0-9]*$")` doing ? It seems to  [cause errors for some people](https://forum.freecadweb.org/viewtopic.php?f=20&t=34806&p=448159#p448159). On Windows, and for me (Ubuntu) it doesn't do anything.

**Comment by wang02139** [comment]
It checks for valid variable names. e.g. "a-b" is not allowed as a variable
name.

**Comment by Zolko-123** [comment]
Yes, I've seen that, thank-you. But there was a missing 
`import re`

**Comment by wang02139** [comment]
Thanks

**Pull request merged**
