### PR TITLE
Tutorial1.md: markdown tweaks

### PR DESCRIPTION
**Pull request by luzpaz**
FIxed a few typos as well

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/FreeCAD_Assembly4/blob/tutorial-tweek/Resources/TUTORIAL1.md

**Comment by luzpaz** [comment]
@Zolko-123 ping

**Comment by luzpaz** [comment]
darn, i need to make sure the image paths are correct..on sec

**Comment by Zolko-123** [comment]
yeah, sorry, I moved the TUTORIAL files around, but if you agree I'll let them be where they are now. Can I merge your fixes ?

**Comment by luzpaz** [comment]
Let you know if just a minute

**Comment by luzpaz** [comment]
@Zolko-123 ready for merge

**Comment by Zolko-123** [comment]
nice, everything works, thanks

**Pull request merged**
