### PR TITLE
Fix AttachExtension::Support property rename

### PR DESCRIPTION
**Pull request by 3x380V**
Fix https://github.com/FreeCAD/FreeCAD/pull/12714 consequences.

### CODE REVIEW

**Comment by Zolko-123** [comment]
Thanks. I wanted to cherry-pick this one but I don't know how to do it. Could you explain how I could have merged it without a PR ?

**Comment by Zolko-123** [comment]
@3x380V  : are **ladis** in the forum ?

**Comment by 3x380V** [comment]
yes, as you an guess from my name used in commit author and as mentioned in my forum profile (not sure if that can be seen by unregistered users)

**Comment by Zolko-123** [comment]
If the question about maintainership of the stable 0.21 version arises, may I ask you to give the idea your thoughtful consideration please ?

**Comment by 3x380V** [comment]
Yes, of course.

**Pull request merged**
