### PR TITLE
Match positive directions on LCS axis too

### PR DESCRIPTION
**Pull request by Jolbas**
When axis is X or Y on LCS. Match positive direction for remaining axis with Placer.Base positive directions

### CODE REVIEW

**Comment by Jolbas** [comment]
The only reason is that they are constants and that way I avoid recreate them on every function call. Not that this is a very expensive calculation. Maybe a good idea to prefix them with underscore.

**Comment by Zolko-123** [comment]
OK. But then, what about putting them in the file [Asm4_libs](https://github.com/Zolko-123/FreeCAD_Assembly4/blob/master/Asm4_libs.py#L554) as other global static parameters ?

**Comment by Jolbas** [comment]
Absolutely. I fix it.
I noticed when looking as [Asm4_measure](https://github.com/Zolko-123/FreeCAD_Assembly4/blob/master/Asm4_Measure.py#L1043).py the methods isVector, isCircle, isLine, isSegment and isFlatFace are also present in [Asm4_libs](https://github.com/Zolko-123/FreeCAD_Assembly4/blob/master/Asm4_libs.py#L554) but as functions. How about using the Asm4_lib functions instead because they don't use the self argument anyway? I can fix in same PR if there are no reasons behind.
Then if you think the mirror command works fine as derived from ExpressionArray I can remove the entire mirrorPartCmd.py

**Comment by Jolbas** [comment]
I make a separate cleanup PR in that case. Won't add more to this one.

**Comment by Zolko-123** [comment]
Thanx. I might re-order and/or rename the constants to a more consistent naming.

**Comment by Jolbas** [comment]
Sure. I didn't have a good name for the (1,1,1) vector.

**Pull request merged**
