### PR TITLE
Enable/Disable 3D view Link selection mode

### PR DESCRIPTION
**Pull request by abetis**
Adding toolbar button to enable/disable select mode.
Unfortunately it looks like there is no way to update the icon after addition of the command on initialization.
All I could do is add a printout that says if the mode was enabled or disabled.

### CODE REVIEW

**Comment by Zolko-123** [comment]
I think there was a question about such a toggle-switch in the forum, and it might not be possible to do. For sure it's not possible to change the icon.

**Comment by Zolko-123** [comment]
I changed the icon and streamlined the function. I think it's actually very good, thank-you.

There is something that could be improved: allow this functionality not only for linked objects but Parts and Bodies. And also Fasteners.

**Comment by abetis** [comment]
Fasteners are not linked parts?

**Comment by Zolko-123** [comment]
> Personally I need that mode of selection in general working mode, not in the insertLink.

but it doesn't work for measures for example: if you want to measure the distance between de centres of 2 circles, the link selection mode is in your way. Enabling/disabling it works well, thank-you

**Comment by Zolko-123** [comment]
no, fasteners are not linked parts.

**Comment by abetis** [comment]
ok, got it

**Comment by Zolko-123** [comment]
> 
> 
> Adding toolbar button to enable/disable select mode.
> Unfortunately it looks like there is no way to update the icon after addition of the command on initialization.
> All I could do is add a printout that says if the mode was enabled or disabled.

There is a way now, see 
https://forum.freecadweb.org/viewtopic.php?f=23&t=55958&p=481531#p481531

**Pull request merged**
