### PR TITLE
Improve organization of python files

### PR DESCRIPTION
**Pull request by leoheck**

### CODE REVIEW

**Comment by leoheck** [comment]
This PR moves python files to a folder
```
mkdir asm4
mv *.py asm4
```

and the update on the paths of one file and one folder:
```
VERSION -> ../VERSION 
Resources/ -> ../Resources/
```

It also updates the `.gitignore` accordingly.

**Comment by leoheck** [comment]
Hi @Zolko-123, are you interested in improving the organization of this repo? This way more people can help to improve it. This is a similar organization that other workbenches follow on their repositories.

Changes here are quite small actually despite what this PR window shows. 

These changes improve a lot the main page of the project in GitHub. It also makes it easier to understand the repository if you are a dev that wants to contribute to the project.

**Comment by Zolko-123** [comment]
To be honest I don't have much time now so I'm not convinced by shuffling code unnecessarily around. What matters is the content of the Mod directory not the Git page.

**Comment by Zolko-123** [comment]
not the current plan

**Comment by Zolko-123** [comment]
actually, I'm going to do this to make the GitHub project page better readable. I'll call the additional directory _Code_ though, not _asm4_

**Comment by leoheck** [comment]
Everything is `Code`. Whatever. This is an interesting step towards organization. This repo looks like a pile of trash.

**Comment by leoheck** [comment]
> actually, I'm going to do this to make the GitHub project page better readable. I'll call the additional directory _Code_ though, not _asm4_

Hey, what happen to this idea?

**Pull request closed without merging**
