### PR TITLE
super infoPart and makeBom

### PR DESCRIPTION
**Pull request by FarmingSoul**
the infoPart all configurable with manuel field and auto filling field.
and there is a manage for the future add of new auto-field in Asm4 update.
you can use directly BoM without worrying about filling in the partInfo fields.
I write only in english and i comment the code and i clean it .
Try a commit in freeCAD before read the code in detail.

### CODE REVIEW

**Comment by FarmingSoul** [comment]
start without BoM and PartInfo on Part
0-start
I can make directly a BoM - all the auto filling field will be fill and a manual field stay blank. - BoM give me a Log
1-direct
and when i press OK he directly emene me in my BoM Spreadsheet
2-direct-ok
i can open Edit Part Info
3-epi
i can open config in Edit Part Info
4-epi-config
in config in Edit Part Info i can change name of field - active and disactive all field - add and delete manual field
5-epi-config-add-delete
when i press ok the config it save on file
6-epi-config-ok
you can see a new BoM with new config 
7-newbom-with newconf
when we update Asm4 with new autofilling field that was not before
8-newautofieldinasm4update
the user can add our new autofilling field in Edit Part Info - Config
9-epi-config-update

**Review by Zolko-123 — CHANGES_REQUESTED** [review]
Can you please separate the translation and the software commits ?

**Comment by Zolko-123** [comment]
ALSO: please look at the following forum topic:

https://forum.freecadweb.org/viewtopic.php?f=22&t=62284

it describes how to use JSON files for user-configurations. If we make the PartInfo a dictionary (key, value) then we can save that dictionary in a JSON file in the user config directory, or even better in a dub-directory that we should call "Templates":

```
templateDir = os.path.join(App.getUserAppDataDir(),'Templates')
filename = "ProjectX_PartInfo.json"
filepath = os.path.join(templateDir, filename)
PartInfo = {'PartID' : '' , 'PartName' : '' , 'Project' : 'X' , 'Supplier' : ''}

import json

with open(filepath,"w") as outfile:
    json.dump(PartInfo,outfile)

f = open(filepath)
some_other_dictionary = json.load(f)
f.close()
```

and ideally, we would call a Qt file open dialog (or save). 

Because the way to store the user keys in the workbench directory is dangerous as it might get overwritten, or even deleted, by an update.

**Comment by FarmingSoul** [comment]
Thank you for all.
I make what you say when a take a time and i come back to you.
otherwise how you think about this commit ? have test it ? have you try to make a new autoinfofield ?.... ?

**Comment by xoviat** [comment]
@FarmingSoul To be frank, I realized that I want to continue using my own macros for generating BOMs. I am sorry for any delays that I caused to this, I will be fine with any changes that @Zolko-123 is happy with. I don't really have time to look into this further, and I realized that I shouldn't criticize others who are trying to moving something forward. From the images that you posted, it looks fine.

**Comment by totalcad** [comment]
Hello @FarmingSoul , @Zolko-123 !
I don't know is it right to write here../
I've tested v.0.11.1 - BOM works well (even with russian(cyrillic) names)! Thank you!
But the Edit Fields functionality is missing. Is it right (I mean it is not implemented yet)? Or it must work..
Edit_field_notworking
(I'm in Ubuntu 20.04.3, FreeCad0.19 official from repository)

**Comment by Zolko-123** [comment]
the BoM is in active development, see https://github.com/Zolko-123/FreeCAD_Assembly4/pull/253. you can try the development branch, it would be great if you could test it too

**Comment by totalcad** [comment]
@FarmingSoul 
Also I've made another forum topic about one more thing which we could count in BOM - electric cables:
https://forum.freecadweb.org/viewtopic.php?f=20&t=62675
Steel it's a very difficult way to do such task, but as a potential possibility - it is very attractive! "Line.Shape.Length" expression works well with Draft "Line" 3D sketch (polyline tool) - so I've used this "polyline" from Draft as the "path" for Sweep tool from Part Design WB in making cables.

**Comment by totalcad** [comment]
@Zolko-123 Ou, thankx Zolko! Super! I'll test with pleasure!!

**Comment by totalcad** [comment]
@Zolko-123 , sorry, I'm not a programmer... "you can try the development branch" - is it difficult to do? I mean I need to compile something or similar? Can I download some files end replace somewhere in my Assembly4 folder?

**Comment by Zolko-123** [comment]
Download the ZIP (https://github.com/Zolko-123/FreeCAD_Assembly4/archive/refs/heads/development.zip), extract it into the FreeCAD Mod directory (/home/totalcad/.FreeCAD/Mod), and remove the existing Assembly4 folder there

**Comment by totalcad** [comment]
Thank you ZolkO!
Tasted your steps!
Asm4 can't launch or something similar..
Screenshot from 2021-10-04 02-03-34
.
After pressing Ok:
Screenshot from 2021-10-04 02-05-37

**Comment by Zolko-123** [comment]
yes, sorry, please try again

**Comment by totalcad** [comment]
Now I can test! Thank you!

**The result:**

Successful adding a new fields!:
adding_fields

But values of desired new parameters are not stored:
doesnt_save_values

The bom generating without values
bom_no_values
:

**Comment by Zolko-123** [comment]
@totalcad : for me it works as advertised

@FarmingSoul : looking inside the code, on top of what I've said before, the _drawUI()_ function must only do that: draw the UI elements, and NOT do any other function (like 

```
        if self.infoTable[0][1]=='':
            self.infoDefault()
            self.addNew()
```

Also, in _infoPartConfUI()_, please call that _drawUI()_ also (and not _drawConfUI()_), and separate the logic from the UI please, this in order to make the code maintainable in the long term.

**Comment by Zolko-123** [comment]
oups: please us https://github.com/Zolko-123/FreeCAD_Assembly4/pull/253

**Comment by totalcad** [comment]
@Zolko-123 @FarmingSoul - guys you are incredibly cool!!!
I've made a new laser sheet file and accidentally noticed Part Info in Property!

part_info_in_property


It's so powerful when I've added an expression "Sketch.Shape.Length"!:
laser_asm4_bom_espressions

**THANK YOU!!** :+1: :)

[laser_perimeter.zip](https://github.com/Zolko-123/FreeCAD_Assembly4/files/7277304/laser_perimeter.zip)

**Comment by totalcad** [comment]
@Zolko-123 
I can't reproduce the bug about not stored values. Just my new files are working good. I can't figure out what I've done, but in the old file with the bug I've found the redundant fields. May be this is the problem. I don't know how to delete them, because they don't present in the Edit Fields dialog:
redudant_fields
.

**Comment by FarmingSoul** [comment]
@totalcad 

make that and i add a réinit button in part info
```

a=App.getDocument('_____________1').getObject('_____________1')
list=a.PropertiesList
listpi=[]

for prop in list :
 	if a.getGroupOfProperty(prop) == 'PartInfo' :
 		listpi.append(prop)
		
for suppr in listpi :
 	a.removeProperty(suppr)
```

**Comment by FarmingSoul** [comment]
@totalcad 

i know what is your bug 

you have try to use cirilic as new field so :

he try to write in cirilic in your userConfFile , it work
he try to write in cirilis in your part.PartInfo propriety but he only write "_______"

after when you open PartInfo
he look if your name in cirilic (of your userConfigFile)  exist in Part Info propriety of part <-False so :
he try to write in cirilis in your part.PartInfo propriety but he only write "_______" with 1 ,2 ,3 ...

so actualy you can use cirilic as PartInfo Field !
sorry .
@Zolko-123 


>

**Comment by totalcad** [comment]
Hi, @FarmingSoul !
Yes I've tested - the problem presents with russian and also with some french (çëàùù) symbols:
lang_symbols_problem

**Comment by Zolko-123** [comment]
> the problem presents with russian and also with some french (çëàùù) symbols

this is a known FreeCAD issue, there is nothing we can do about

**Comment by totalcad** [comment]
> 
>     the problem presents with russian and also with some french (çëàùù) symbols
> 
> this is a known FreeCAD issue, there is nothing we can do about

@Zolko-123 , thanks for the clarification! Yes, again this problem - I've just remembered I've already opened in forum :)). May be I'll try to discuss this in forum with the "main core FC" developers...
BUT the BOM in such stage as it is for now - is already super duper cool!!
Thank you!

**Comment by FarmingSoul** [comment]
@totalcad @Zolko-123 
it workable for (çëàùù) symbols i hope it's the same for russian !
Capture
Capture2
view this pr #257

**Comment by FarmingSoul** [comment]
@totalcad 
>@FarmingSoul , @Zolko-123
>Is it possible to avoid an alphabet arrangement, because it would be comfortable to have a user defined order of fields (IMO)? >This takes effect in the BOM also:

i care about that tomorow but i have question:
you want the good order in BoM only (because it's easy)(and it's very useful)
or you want the good order in partInfoUI ??(because it's more hard)(and it's less useful)(but it's better)

**Comment by totalcad** [comment]
Hi, @FarmingSoul !
"the good order in BoM only" - is enough for me! I'm very grateful!
Is there a way to get and test your "workable for (çëàùù) symbols" version? :)
Thanks!

**Comment by totalcad** [comment]
I mean I can't understand how to get from "view this pr #257"?

**Comment by totalcad** [comment]
I've decided to learn French a little..:)
I've made a fields with french symbols and when I decided to add a formulas to the properties - I've found the strange symbols in the properties fields. That's not a big problem - I can remember the order of fields and fill the properties. The BOM works well anyway, when the property is filled:
property_symbols

files:
[a4_testing.zip](https://github.com/Zolko-123/FreeCAD_Assembly4/files/7289125/a4_testing.zip)

**Pull request closed without merging**
