### PR TITLE
changes for loadtemplate

### PR DESCRIPTION
**Pull request by FarmingSoul**
for remake workable partInfoUI and makeBom

### CODE REVIEW

**Comment by FarmingSoul** [comment]
Hello @Zolko-123 ,

Thanks for the cleaning

**Comment by Zolko-123** [comment]
out of sync

**Comment by FarmingSoul** [comment]
hello,
what you mean about 'out of sync' ?

**Comment by Zolko-123** [comment]
I have modified the file while you modified it also, so they can't be merged. And your changes where minimal anyway. I won't touch them so you clean up. Thanx

**Pull request closed without merging**
