### PR TITLE
Organization proposal

### PR DESCRIPTION
**Pull request by leoheck**
I am proposing to organize the repo keeping python files inside a folder. 
It keeps the root path (and the initial page of the GitHub) shorter
It also helps to find python files easier. 

This also adds `anytree` as dependency so it will be listed with the Addon Manager as it was stated here:
https://forum.freecad.org/viewtopic.php?t=76394

What do you think?

### CODE REVIEW

**Comment by Zolko-123** [comment]
Too much work for no identifiable gain

**Comment by Zolko-123** [comment]
> This also adds `anytree` as dependency so it will be listed with the Addon Manager

please do not mix different functionalities in 1 PR

**Comment by leoheck** [comment]
It is just a single work. Organization (moving files to a new folder)... for that, some paths were updated too.

**Comment by leoheck** [comment]
I will split this update in 2 then

**Pull request closed without merging**
