### PR TITLE
Improve BOM part 3

### PR DESCRIPTION
**Pull request by leoheck**
It Fixes the greedy walk for some specific cases.
Improves console messages with better information
Present parts in the same order they appear, making it easier to verify if the BOM is right.

Now my designs that were made recently with 0.21 and Asm4 work nicely. And also, the design of @hasecilu that is big, complex but quite right. 

This is a late fix. Sorry for too many PRs @Zolko-123

### CODE REVIEW

**Comment by leoheck** [comment]
Ah found something else.
Links of Fasteners.
This may be a bug, but I think it is a unsupported feature.

@hasecilu how did you make those links?

@Zolko-123, does Asm4 should accept having links to Fasteners?
If so, I have to add this part to be treated in the BOM

image

**Comment by hasecilu** [comment]
I made an update minutes ago in my `testing` branch, (don't include this PR).

I included the Fasterners_BOM created by the Fasteners WB and it includes the correct number of Fasteners, in this script (https://github.com/shaise/FreeCAD_FastenersWB/blob/master/FastenerBase.py) the `GetTotalObjectRepeats(obj)` seems to be the function that count elements and it's able to count `Links` like the ones I used a lot, maybe it could be taken as reference. I think the magic line is the 315

**Comment by leoheck** [comment]
cool, I will test. but the messages here are still good and valid. 
i am going to upgrade the pr accordingly.
but I am going to have lunch now, so I come back right after

**Comment by hasecilu** [comment]
> @hasecilu how did you make those links?

I made the links this way: https://youtu.be/tltsTgfC3U8?t=51
The same for Link in fasteners and other models like Sliding nuts or some Al profiles

**Comment by leoheck** [comment]
It looks like it has to be supported since Fasteners are. I will check how to do it.

**Comment by leoheck** [comment]
Almost there. It works for the ASSembly.FCStd file (fastener links inside a folder)
When the fastener link is right under the Model, the count is 1 less. =/

**Comment by hasecilu** [comment]
I have just tested the code and can confirm it, it's odd

**Comment by leoheck** [comment]
I could finish!

**Comment by leoheck** [comment]
I am about to commit.

**Comment by leoheck** [comment]
Alright, now it looks like it is working for all the scenarios I am aware of.

**Comment by hasecilu** [comment]
The last fix is working.
I detected another scenario: when you use the same type of fastener without using the `Link` function both appear in the BOM but in different rows.

I like to use the `Link` function because the new fasteners inherit the properties of the main one like type, length, material, etc. It's totally valid don't using `Links` but you need to change manually for every copy.

Same_fast

**Comment by leoheck** [comment]
I tried that, it was working for me. I think you are doing some black magic haha. Well, if this SW_X file is in your repo I will try to check this file myself to see if it is different here.

**Comment by leoheck** [comment]
I added the screw and nuts, and here, they are right.
image
image

**Comment by leoheck** [comment]
What is the version of your Freecad again?

**Comment by leoheck** [comment]
Ah, I updated the repo, and your file is there with your screws, got the same behavior.

**Comment by leoheck** [comment]
It is a bit odd the way you add the screws. I am using the ones in the Asm4 panel.

**Comment by leoheck** [comment]
Console log, the last column (obj.Label) is different from your file and mine. 
I could use the obj.Name to check if they are the same. But this is not good =/ since this cannot be changed by the user

# hasecilu
```
21:33:55  ASM4> [1]    | App::Link | SW_X#LimitSW_CNC_1 | LimitSW_CNC 1
21:33:55  ASM4> [2]        | 1x | App::Part | Limit_SW_PCB#Part001 | LimitSW_CNC 1
21:33:55  ASM4> [1]      | 1x | Part::FeaturePython | SW_X#Screw | M3x14-Screw
21:33:55  ASM4> [1]      | 1x | Part::FeaturePython | SW_X#Screw001 | M3x14-Screw001
21:33:55  ASM4> [1]      | 1x | Part::FeaturePython | SW_X#Nut | M3-Nut
21:33:55  ASM4> [1]      | 1x | Part::FeaturePython | SW_X#Nut001 | M3-Nut001
```
image


# MINE
```
21:36:21  ASM4> [1]    | App::Link | SW_X#LimitSW_CNC_1 | LimitSW_CNC 1
21:36:21  ASM4> [2]        | 1x | App::Part | Limit_SW_PCB#Part001 | LimitSW_CNC 1
21:36:21  ASM4> [1]      | 1x | Part::FeaturePython | SW_X#Screw | M3x8-Screw
21:36:21  ASM4> [1]      | 2x | Part::FeaturePython | SW_X#Screw001 | M3x8-Screw
21:36:21  ASM4> [1]      | 1x | Part::FeaturePython | SW_X#Nut | M3-Nut
21:36:21  ASM4> [1]      | 2x | Part::FeaturePython | SW_X#Nut001 | M3-Nut
```

image

**Comment by leoheck** [comment]
When I update something, the fasteners on your design are normalized to have the same name (I mean, label)
image

**Comment by hasecilu** [comment]
> What is the version of your Freecad again?

snap of FreeCAD Link Branch edge branch, it contains the latest changes of reathunder, I have tried to open it in 0.21 but the ASSembly gets scrambled.

**Comment by hasecilu** [comment]
> It is a bit odd the way you add the screws. I am using the ones in the Asm4 panel.

I used the Fastener button included in Assembly4

**Comment by leoheck** [comment]
And the version of the Fastener WB?

**Comment by leoheck** [comment]
A fix that I am making is to remove the digits from the end of the Label... considering the Fastners did not normalize the names yet. But I would like to know how to normalize fasteners names.

**Comment by hasecilu** [comment]
I changed of computer, but is one of the latest versions, less than a week at most

**Comment by leoheck** [comment]
This last commit will solve this particular issue with Fastners.

**Comment by leoheck** [comment]
Could you check?

**Comment by leoheck** [comment]
I bet we can find more issues, but they are definitely getting harder to find.

**Comment by leoheck** [comment]
Sure, take your time.

**Comment by hasecilu** [comment]
In `Edit > Preferences >  General > Document > Document objects `, do you have checked "Allow duplicate objects labels in one document"? I don't and thats why I think in my file it gets the 001 suffix.

**Comment by leoheck** [comment]
You are right, I have this checked. But I thought the renaming process was a feature of the Fasteners.  Actually, you are right. But the last fix should work for you too.

**Comment by hasecilu** [comment]
Yeah, the latest commit fixed it!

**Comment by leoheck** [comment]
Good! Thanks, @Zolko-123 this is ready to be merged.

**Comment by hasecilu** [comment]
Now we can wait to hear users with different workflows if the new BOM works for them, having 2 separate BOM options is really handy. Thanks for your work!

**Comment by leoheck** [comment]
Totally. If you know someone, just ask them to test it, please.

**Comment by Zolko-123** [comment]
Thank-you. Unfortunately I have no time to test in these days, sorry

**Pull request merged**
